#
#------------------------------
#     Format Guidelines:
#------------------------------
#
# You can create your own "drink events," every event needs the following format
# event-name:
#   action: [actionType]
#   instruction: [String to be displayed upon action completion]
#   drinkValue: [# of drinks]
#
#            OR
#
# event-name:
#   action: [actionType]
#   instruction: [String to be displayed upon action completion]
#   drinkMin: [minimum number of drinks]
#   drinkMax: [maxmimum number of drinks]
#
# The later picks a random integer between the drink minimum and maximum (inclusive)
#
#
# There are a number of optional parameters that can be added to any event:
# 1) reason: [String giving reason to player for drinking]
# 2) broadcastMessage : [String giving reason that will be broadcast for other players to see]
# 3) giveReason: [True/False, specifies whether the player will receive any reason for drinking
# 4) chance: [0.0 - 1.0, the chance the player has to drink for this action]
# 5) cooldown: [The time in seconds before the player can drink for this action action]
# 6) drinksToGive: [amount of drinks a player can give out to drink]
#
#
# In strings you can use the following placeholders:
# 1) $playerName$ (replaces this part of the string with the player's name)
# 2) $drinkValue$ (number of drinks the game decides the player takes)
# 3) $drinksToGive$ (number of drinks the player gives)
# 3) $drinks$, $shots$, $sips$, $chugs$ all can be used to represent the proper grammar for the amount of drinks#
#    i.e they will have an 's' at the end if drinkValue is not 1.
#
#
# There are a number of possible actions. With most actions you can add a condition (listed under them)
# For example, you can specify what type of block broken causes a "drink event"
# Not specifying a condition means any time the event occurs, a drink event will occur.
#
#
# POSSIBLE ACTIONS:
# 1) BREAK_BLOCK
#    a) blockType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
# 2) CHAT
#    a) message
#    b) messageContains
# 3) CONSUME
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
# 4) DIE
#    a) damageCause (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html for choices)
#    b) killer (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
# 5) DROP
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
#    b) amount
# 6) FISH
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
# 7) GET_ADVANCEMENT [Not currently working]
#    a) advancement
# 8) HARVEST
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
#    b) amount
# 9) INTERACT
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
#    b) isRightClick (True or False)
#    c) isLeftClick  (True or False)
# 10) INTERACT_ENTITY
#    a) entity (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
# 11) ITEM_BREAK
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
# 12) JOIN
# 13) KILL
#    a) entity (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
# 14) LEVEL_CHANGE
#    a) levelAchieved
# 15) MEND
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
# 16) MOVE
#    a) speed
# 17) PICKUP
#    a) itemType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
#    b) amount
# 18) PLACE_BLOCK
#    a) blockType (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for choices)
# 19) TAKE_DAMAGE
#    a) damageCause (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html for choices)
# 20) TAME
#    a) entity (see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html for choices)
# 21) TELEPORT
#    a) teleportCause (see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerTELEPORTEvent.TELEPORTCause.html for choices)
#    b) distance
#
# There are examples below, they can be editted or reMOVEd
# You can also add your own.

dying:
  action: DIE
  instruction: 'Finish drink'
  drinkValue: 5

taking-fall-damage:
  action: TAKE_DAMAGE
  instruction: 'Take $drinkValue$ $drinks$'
  drinkValue: 1
  actionConditions:
    damageCause: FALL

entity-explosion:
  action: TAKE_DAMAGE
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 1
  cooldown: 5
  actionConditions:
    damageCause: ENTITY_EXPLOSION

mining-diamonds:
  action: BREAK_BLOCK
  instruction: 'Pick another player to drink'
  drinkValue: 0
  drinksToGive: 1
  broadcastMessage: '$player$ has gained $drinksToGive$ to assign'
  actionConditions:
    blockType: DIAMOND_ORE

mining-deepslate-diamonds:
  action: BREAK_BLOCK
  instruction: 'Pick another player to drink'
  drinkValue: 0
  drinksToGive: 1
  broadcastMessage: '$player$ has gained $drinksToGive$ to assign'
  actionConditions:
    blockType: DEEPSLATE_DIAMOND_ORE

item-breaking:
  action: ITEM_BREAK
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 1

consuming-potion:
  action: CONSUME
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 1
  actionConditions:
    itemType: POTION

killing-horse:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 3
  actionConditions:
    entity: HORSE

killing-dolphin:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 3
  actionConditions:
    entity: DOLPHIN

killing-golem:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 3
  actionConditions:
    entity: IRON_GOLEM

killing-turtle:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 3
  actionConditions:
    entity: TURTLE

killing-cat:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 9
  actionConditions:
    entity: CAT

killing-villager:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 2
  actionConditions:
    entity: VILLAGER

killing-zombie-villager:
  action: KILL
  instruction: 'Take $drinkValue$ drinks'
  drinkValue: 2
  actionConditions:
    entity: ZOMBIE_VILLAGER

taming-animal:
  action: TAME
  instruction: 'Pick another player to drink'
  drinkValue: 0
  drinksToGive: 1
  broadcastMessage: '$player$ has gained $drinksToGive$ to assign'

killing-player:
  action: KILL
  instruction: 'Take $drinkValue$ $drinks$'
  drinkValue: 1
  actionConditions:
    entity: PLAYER

fire-damage:
  action: TAKE_DAMAGE
  instruction: 'Take $drinkValue$ $drinks$'
  drinkValue: 1
  cooldown: 30
  actionConditions:
    damageCause: FIRE

lightning-damage:
  action: TAKE_DAMAGE
  instruction: 'Take $drinkValue$ $drinks$'
  drinkValue: 1
  cooldown: 5
  actionConditions:
    damageCause: LIGHTNING

breaking-spawner:
  action: BREAK_BLOCK
  instruction: 'Pick another player to drink'
  drinkValue: 0
  drinksToGive: 5
  broadcastMessage: '$player$ has gained $drinksToGive$ to assign'
  actionConditions:
    blockType: SPAWNER


